Sprint 3
artemii258/middle.messenger.praktikum.yandex pull request #7
Opened 2023-02-18 10:12 UTC by artemii258

2023-02-19 10:18 UTC, podlovchenko requested changes
Привет, спасибо за проделанную работу, в целом все хорошо, есть несколько замечаний
1. Есть ошибки типизации, можно посмотреть выполнив команду `tsc --noEmit`
2. Было бы отлично добавить в package.json команды для запуска линтеров
3. Нет редиректа, если пользователь уже в системе

2023-02-19 10:18 UTC, podlovchenko commented on src/Controllers/MessagesController.ts
> +export default controller;
Использование дефолтных экспортов, на мой взгляд, это не очень хорошая практика.

Они позволяют задавать разные имена импортируемым объектам, из-за этого страдает читабельность, экземпляры с разными именами очень трудно потом искать по проекту. Так же затрудняется рефакторинг таких импортов.

Если задавать обычный экспорт, мы можем быть почти везде точно уверены, что имена используются везде одинаковые и IDE в таком случае спокойно их сможет поменять в случае рефакторинга.

Хорошая статья на эту тему
https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

2023-02-19 10:18 UTC, podlovchenko commented on src/Controllers/MessagesController.ts
> +window.messagesController = controller;
Для чего?

2023-02-19 10:18 UTC, podlovchenko commented on src/pages/chats/_chats.scss
>  			input {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2023-02-19 10:18 UTC, podlovchenko commented on src/pages/mainPage/MainPage.ts
> +// 			}
Закомментированный код лучше не оставлять в проекте

2023-02-19 15:33 UTC, artemii258 commented on src/Controllers/MessagesController.ts
> +export default controller;
в контроллерах поменял, буду знать.

2023-02-19 15:34 UTC, artemii258 commented on src/Controllers/MessagesController.ts
> +window.messagesController = controller;
удалил, не пригодилось

2023-02-19 15:36 UTC, artemii258 commented on src/pages/chats/_chats.scss
>  			input {
да так лучше, но у меня с классом '-input' 100% всегда лежит input и label

2023-02-19 15:36 UTC, artemii258 commented on src/pages/mainPage/MainPage.ts
> +// 			}
удалил все папку

2023-02-19 15:39 UTC, artemii258 commented
дипизацию исправил, редирект авторизованного пользователя в чаты сделал, в package.json добавил линтер tsc.

2023-02-20 10:06 UTC, podlovchenko requested changes
Привет, есть ошибка при сборке 
<img width="556" alt="Снимок экрана 2023-02-20 в 13 06 20" src="https://user-images.githubusercontent.com/22602747/220075107-5640d002-6e21-48f4-a4a1-31b895265961.png">

2023-02-20 10:06 UTC, podlovchenko commented on package.json
> +		"noEmit": "tsc ---noEmit",
Лишний дефис
```suggestion
		"noEmit": "tsc --noEmit",
```

2023-02-20 12:18 UTC, podlovchenko commented
Работу принимаю)

2023-02-20 13:11 UTC, merged